blocked-commands:
  - 'pl'
  - 'plugin'
  - 'plugins'
  - 'ver'
  - 'version'
  - 'help'
  - '?'
  - 'seed'
  - 'save-all'
  - 'save-off'
  - 'save-on'
  - 'stop'
  - 'reload'
  - 'rl'
  - 'op'
  - 'deop'
  - 'list'
  - 'kill'
  - 'xp'
  - 'say'
  - 'bukkit:pl'
  - 'bukkit:plugins'
  - 'bukkit:version'
  - 'bukkit:help'
  - 'bukkit:?'
  - 'minecraft:pl'
  - 'minecraft:plugins'
  - 'minecraft:version'
  - 'minecraft:help'